# Generated by Django 5.2.1 on 2025-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Wing Team', 'Wing Team'), ('Fuselage Team', 'Fuselage Team'), ('Tail Team', 'Tail Team'), ('Avionics Team', 'Avionics Team'), ('Assembly Team', 'Assembly Team')], max_length=20),
        ),
    ]
